# =====================
# ADMIN DEPLOYMENT
# =====================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: subbarayudu2011/doctor-admin:latest
          ports:
            - containerPort: 5174

---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  type: NodePort
  selector:
    app: admin
  ports:
    - protocol: TCP
      port: 5174
      targetPort: 5174
      nodePort: 30174

# =====================
# CLIENT DEPLOYMENT
# =====================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: subbarayudu2011/doctor-client:latest
          ports:
            - containerPort: 5175

---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  type: NodePort
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 5175
      targetPort: 5175
      nodePort: 30175

# =====================
# SERVER DEPLOYMENT
# =====================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: subbarayudu2011/doctor-server:latest
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: MONGO_URI
              value: "mongodb+srv://Subbarayudu:Subba@cluster0.tzkcl.mongodb.net"

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 4000
